USE SudOuest
GO

--CREATE SCHEMA import
--GO
--CREATE SCHEMA rejet
--GO

--IC 191 "MOTIFS DE DISTRIBUTION" (ANNULE ET REMPLACE) 
IF OBJECT_ID(N'import.IC_MOTIFS_DE_DISTRIBUTION') IS NOT NULL
    DROP TABLE import.IC_MOTIFS_DE_DISTRIBUTION
GO
 
CREATE TABLE import.IC_MOTIFS_DE_DISTRIBUTION
(
	CODMOT     NVARCHAR(255) NULL
   ,LIBMOT     NVARCHAR(255) NULL
)
GO


--IC192	"REFERENTIEL VOIES ILOTS" (ANNULE ET REMPLACE) * :
IF OBJECT_ID(N'import.IC_REFERENTIEL_VOIES_ILOTS') IS NOT NULL
    DROP TABLE import.IC_REFERENTIEL_VOIES_ILOTS
GO
 
CREATE TABLE import.IC_REFERENTIEL_VOIES_ILOTS
(
	CODDEP     NVARCHAR(255) NULL
   ,IMPMIN     NVARCHAR(255) NULL
   ,IMPMAX     NVARCHAR(255) NULL
   ,PAIMIN     NVARCHAR(255) NULL
   ,PAIMAX     NVARCHAR(255) NULL
   ,INS        NVARCHAR(255) NULL
   ,CODILO     NVARCHAR(255) NULL
   ,MOTPRE     NVARCHAR(255) NULL
   ,MOTDEU     NVARCHAR(255) NULL
   ,NOM        NVARCHAR(255) NULL
   ,TYP        NVARCHAR(255) NULL
   ,DESASC     NVARCHAR(255) NULL
   ,CODBLO     NVARCHAR(255) NULL
   ,CODPOS     NVARCHAR(255) NULL
   ,BUREAU     NVARCHAR(255) NULL
   ,MANAUT     NVARCHAR(255) NULL
   ,NIVTRC     NVARCHAR(255) NULL
   ,TYPGRP     NVARCHAR(255) NULL
   ,MOTGRP     NVARCHAR(255) NULL
)
GO

--IC218	"TITRES" (ANNULE ET REMPLACE) 
IF OBJECT_ID(N'import.IC_TITRES') IS NOT NULL
    DROP TABLE import.IC_TITRES
GO
CREATE TABLE import.IC_TITRES
(
	CODSOC     NVARCHAR(255) NULL
   ,CODTIT     NVARCHAR(255) NULL
   ,LIBCOU     NVARCHAR(255) NULL
   ,LIBLNG     NVARCHAR(255) NULL
)
GO

-- IC253 "APPLICATION ANNEXES" (ANNULE ET REMPLACE)
IF OBJECT_ID(N'import.IC_APPLICATION_ANNEXES') IS NOT NULL
    DROP TABLE import.IC_APPLICATION_ANNEXES
GO
CREATE TABLE import.IC_APPLICATION_ANNEXES
(
	NUMABO     NVARCHAR(255) NULL
   ,APPCOD     NVARCHAR(255) NULL
   ,APPABO     NVARCHAR(255) NULL
)
GO

-- IC257 "ROFF01" (PARAMETRE DES OFFRES OPTIONS)
IF OBJECT_ID(N'import.IC_ROFF01') IS NOT NULL
    DROP TABLE import.IC_ROFF01
GO

CREATE TABLE import.IC_ROFF01
(
	ROFCODSOC     NVARCHAR(255) NULL
   ,ROFCODTIT     NVARCHAR(255) NULL
   ,ROFCODOFF     NVARCHAR(255) NULL
   ,ROFOPT        NVARCHAR(255) NULL
   ,ROFSOCOPT     NVARCHAR(255) NULL
   ,ROFTITOPT     NVARCHAR(255) NULL
   ,ROFSEQTIT     NVARCHAR(255) NULL
   ,ROFCODPRO     NVARCHAR(255) NULL
   ,ROFVALPRO     NVARCHAR(255) NULL
)
GO
